flywheel subsystem code, tried it in sim and it entered all the state…
CaitlynFong/2020-frc-basebot pull request #6
Opened 2020-10-17 18:31 UTC by CaitlynFong

flywheel code
ran in Sim and entered all the states, but i was a little bit confused on what it should display for my opn_flywheels speed and how the velocity and speed would work
needs review

2020-10-17 21:23 UTC, coychanders requested changes
Great work! Most of your code looks perfect. I only found some logic issues in flywheel states. If you updated these, I'll spend some time testing to see what else I can catch.

2020-10-17 21:23 UTC, coychanders commented on src/main/java/org/team1619/behavior/Flywheel_States.java
> +			}
You should move these checks below you button up/down speed adjustments

2020-10-17 21:23 UTC, coychanders commented on src/main/java/org/team1619/behavior/Flywheel_States.java
> +			if (fSharedInputValues.getNumeric("opn_flywheel") > 5500){
Look up this value 5500 instead of hard codeing it

2020-10-17 21:23 UTC, coychanders commented on src/main/java/org/team1619/behavior/Flywheel_States.java
> +		fSharedOutputValues.setNumeric("opn_flywheel", mOutputType, mVelocity, mVelocityProfile);
It appears mVelocity is only set in one condition above

2020-10-17 21:23 UTC, coychanders commented on src/main/java/org/team1619/behavior/Flywheel_States.java
> +				mOutputType = "velocity";
I think you should set the profile here as only velocity has a profile

2020-10-17 21:23 UTC, coychanders commented on src/main/java/org/team1619/behavior/Flywheel_States.java
> +				mVelocity = mSpeed;
I would use another variable and set it to either mVelocity or mSpeed. They way you have it written now, mVelocity is set to speed before the flywheels get up to 5500 and need the original value of mVelocity. Also, the flywheels might bounce above and below 5500.

2020-10-18 21:59 UTC, CaitlynFong commented on src/main/java/org/team1619/behavior/Flywheel_States.java
> +		fSharedOutputValues.setNumeric("opn_flywheel", mOutputType, mVelocity, mVelocityProfile);
Yes, I set mVelocity to mSpeed in one of the statements above and was thinking that the other values would be passed in from the states config. For prime, I was thinking that after speed gets up to 5500, then I would set it equal to velocity from there? I was kind of confused between velocity and speed because wouldn't they be the same numbers, except the direction would be different?

2020-10-18 22:00 UTC, CaitlynFong commented on src/main/java/org/team1619/behavior/Flywheel_States.java
> +				mOutputType = "velocity";
For prime, would it always be pr_prime? I thought since we are using speed to get to 5500 first, there would be no profile until after 5500 is reached.

2020-10-18 22:01 UTC, CaitlynFong commented on src/main/java/org/team1619/behavior/Flywheel_States.java
> +				mVelocity = mSpeed;
So instead of having two variables mVelocity and mSpeed, I should just have one variable for velocity and speed. I was kind of confused on how velocity would equal a number in the thousands, whereas speed is a number between -1 and 1.

2020-10-19 01:52 UTC, coychanders commented on src/main/java/org/team1619/behavior/Flywheel_States.java
> +		fSharedOutputValues.setNumeric("opn_flywheel", mOutputType, mVelocity, mVelocityProfile);
I'm going to try to answer all three of your questions here.

The sequence would be the following.
* flywheel is sitting still
* the system goes into prime
* the motor is set to 0.9 percent to start it spinning up to speed
* the code monitors the velocity
* when the flywheels reach the prime velocity cut off set in the config file (5500) it switches over to velocity mode
* the motor is now set to 6,000 velocity (no longer percent). This requires a PID profile
* if the velocity falls below 5500, it switched back to 0.9 percent
* then back to 6000 velocity when above 5500
* this is all happening in prime
* the operator can adjust the 6000 value at any time. 
* this adjusted value is saved and used the next time the code enters prime

I would create a variable for speed, velocity and velocityadjust.
You read speed and velocity from the state.yaml
Velocityadjust starts at zero, is adjusted through the xbox buttons and saved from state to state.
You also read the velocity and the prime velocity cut off from the state.yaml
If the velocity is below the prime velocity cut off, then use percent mode and the speed value
If the velocity is above, use velocity mode with the velocity set to the velocity variable plus the velocity adjust

Hope this helps. If not, keep asking questions.

2020-10-22 22:24 UTC, merged